Update dev container for Ethereum Relay && Clusters
mangata-finance/mangata-e2e pull request #47
Opened 2021-08-26 22:59 UTC by eddyjlsh

A few features here: 
- The devcontainer will now automatically start a cluster of substrate nodes for development/testing
- The project includes `mangata-{bridge | node | sdk}` as developer dependencies
- A simple cluster test has been added, checking six nodes remain in sync
- Ethereum dependencies for testing/development have been added
- An Eth relayer has been added for testing purposes
- Helper scripts have been included

Might help to demo this due to the high number of file changes, but existing functionality should be unaffected.

2021-09-01 12:15 UTC, goncer commented
@eddyjlsh  it seems that there are some linter issues. Plz fix them otherwise, this PR can not be merged. :)

2021-09-01 12:16 UTC, goncer commented
Maybe some updates in the readme about how to use with new stuff would be useful. what do you think?

2021-09-08 14:50 UTC, goncer requested changes

2021-09-08 14:50 UTC, goncer commented on .github/workflows/lint-test.yml
> +        run: yarn tsc-lint --skipLibCheck
undo!

2021-09-08 14:50 UTC, goncer commented on package.json
> +    "test-cluster": "npx ts-node ./test/cluster/index.ts",
do you mind instead of a index.tx do it in a jest test?

2021-09-08 14:50 UTC, goncer commented on test/cluster/queries.ts
> +import { Node } from "./types";
moe this file to  /utils folder 
plz!

2021-09-08 14:50 UTC, goncer commented on test/cluster/queries.ts
> +import { Node } from "./types";
move**

2021-09-08 14:50 UTC, goncer commented on .github/workflows/lint-test.yml
> +        run: yarn tsc-lint --skipLibCheck
or  keep it ,  IDK :)

2021-09-08 14:50 UTC, goncer commented on test/cluster/api.ts
> +import { ApiPromise, WsProvider } from "@polkadot/api";
plz move this to utils folder

2021-09-08 14:50 UTC, goncer commented on test/cluster/index.ts
> +/* eslint-disable no-console */
plz, 
create a proper test instead of an index.tx :)

2021-09-08 14:50 UTC, goncer commented on test/cluster/types.ts
> +import { ApiPromise } from "@polkadot/api";
maybe move this to utils? 
I think multinode deserves an special subfoldering like UI tests :)

2021-09-08 14:55 UTC, eddyjlsh commented
I agree with all comments but I'm already working on a branch of this branch to add more cluster functionality so I'll merge this and make those changes in that branch.

2021-09-08 15:00 UTC, goncer commented
sure! np

2021-09-08 15:01 UTC, goncer approved these changes

2021-09-09 14:34 UTC, merged